### ISSUE TITLE
Vittu sää oot egogistinen typerys, joka luule olevansa fiksu ja kokee siksi muut uhiksi.

### ISSUE THREAD

**Issue by vivaldev** [Hoosat-Oy/hoosat-template#1]
040 - 705 7347. Soita tai ole varma, että vastaantullessa tää kydään todella läpi. Ootko seonnut tai jotain? Pyydäppä vaiimo lukee toi sun viestin ja katso kasvaako huoli silmäkulmissa. Mää en ole ikinä muuta kuin kunnioittanut sua vertasena, mutta vertainen  on sulle kirosana, koska purat vittu 30v isänä lapsuuden kiusaamistraumoja vissiin. Olsiti vaan puhnut, mutta jos tää näin menee, niin tää puhutaan pikku painin jälkeen, voi luoja, mikä egoistinen kakara ja luulee olevansa fiksu, koska sekoittaa kokemuksen ja yksinäisyyden johonkin taitoihin, joita joku joskus palkkaisi, vaikka näyttää nyt kovasti siltä, että sinä pysyt paikoillas ja yksin koska ihmisille ei vittu sanota kaikkea järjetöntä ja virheellistä paksaa OUT OF THE BLUE. Vitun ididootti. Luulin sua älkykkääksi, nyt oon aika varma että sulla on vaa nii paha persoonallisuushäiriö, narsistinen ja antisosiaalinen ja elättelet suuruusharhaa, joka vie sut vaan ennen pitkää hoitoon, kun sellainen ego ei kestä jatkuvaa opäonnistumista. SOITA KUN TULET JÄRKIISI JA SELITÄ MITÄ VITTUA YRITÄT SANOA NIIN VÄLTÄT SELKÄSAUNAN.

**Comment by TMKCodes** [comment]
Pistän Linkedinissä sulle Crypto bottimme myynti ilmoituksen, sinä rupeat dissaamaan taitojani ja vertaat niitä veljeesi joka opiskellut 2 vuotta cryptoja kun itse olen tehnyt sitä 13 vuotta. Et kestä sanoistasi sarkastista vittuilu palautetta ja rupeat uhkailemaan väkivallalla, kaikki on tallessa ja asia menee poliisin käsiteltäväksi.

Meillä ei ole mitään puhuttavaa.
